import { StyleSheet } from 'react-native';
import { theme } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    ...theme.typography.h3,
    color: theme.colors.text,
    marginTop: 16,
  },
  subtext: {
    ...theme.typography.caption,
    marginTop: 8,
  },
  spriteGrid: {
    padding: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  spriteCard: {
    width: '9.5%', // Approx 10 per row
    aspectRatio: 1,
    backgroundColor: '#1E2228',
    borderRadius: 4,
    padding: 2,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewContainer: {
    width: '100%',
    aspectRatio: 1,
    backgroundColor: '#16191E',
    borderRadius: 2,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  spritePreview: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  pixelGridPreview: {
    width: '100%',
    height: '100%',
  },
  pixelRow: {
    flexDirection: 'row',
    flex: 1,
  },
  pixel: {
    flex: 1,
  },
  spriteLabel: {
    display: 'none', // Hide labels in 8-column view to keep it clean
  },
  fab: {
    position: 'absolute',
    bottom: 30,
    right: 30,
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuContainer: {
    width: 250,
    backgroundColor: '#16191E',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: 4,
  },
  menuTitle: {
    color: theme.colors.text,
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border + '40',
  },
  menuText: {
    color: theme.colors.text,
    fontSize: 16,
    fontWeight: '600',
  },
  detailsContent: {
    width: '100%',
    height: '100%',
    backgroundColor: '#0D0F12',
    borderRadius: 0,
    borderWidth: 0,
    overflow: 'hidden',
  },
  detailsHeader: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#222',
    backgroundColor: '#0D0F12',
  },
  detailsTitle: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
    flex: 1,
  },
  slicerLayout: {
    flex: 1,
    flexDirection: 'row',
  },
  slicerSidebar: {
    width: 200,
    borderRightWidth: 1,
    borderRightColor: '#222',
    backgroundColor: '#0D0F12',
    padding: 8,
  },
  slicerMain: {
    flex: 1,
    backgroundColor: '#050607',
  },
  slicerScroll: {
    flex: 1,
    padding: 8,
  },
  sidebarSection: {
    marginBottom: 12,
  },
  sectionTitle: {
    color: '#555',
    fontSize: 9,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
    flex: 1,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
    height: 20,
  },
  animationPreview: {
    width: 64,
    height: 64,
    backgroundColor: '#000',
    borderWidth: 1,
    borderColor: '#222',
    borderRadius: 2,
    marginBottom: 12,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  inputGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  inputItem: {
    width: '48%',
  },
  label: {
    color: '#444',
    fontSize: 8,
    marginBottom: 2,
  },
  input: {
    backgroundColor: '#111',
    color: '#FFF',
    borderWidth: 1,
    borderColor: '#222',
    borderRadius: 0,
    padding: 4,
    fontSize: 10,
  },
  frameGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 2,
  },
  frameContainer: {
    width: 45,
    height: 60,
    alignItems: 'center',
  },
  frameIndex: {
    color: '#333',
    fontSize: 7,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  frameBox: {
    width: 40,
    height: 40,
    backgroundColor: '#000',
    borderWidth: 1,
    borderColor: '#111',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 0,
    overflow: 'hidden',
  },
  stateList: {
    gap: 4,
  },
  stateItem: {
    backgroundColor: '#111',
    borderRadius: 0,
    padding: 6,
    borderWidth: 1,
    borderColor: '#222',
  },
  stateHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  stateNameInput: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: 'bold',
    flex: 1,
    padding: 0,
  },
  stateActive: {
    borderColor: theme.colors.primary,
    backgroundColor: '#1A1D23',
  },
  stateInputs: {
    flexDirection: 'row',
    gap: 4,
  },
  stateInputWrap: {
    flex: 1,
  },
  addStateBtn: {
    marginTop: 6,
    padding: 6,
    borderRadius: 0,
    borderWidth: 1,
    borderColor: '#222',
    borderStyle: 'dashed',
    alignItems: 'center',
  },
  addStateText: {
    color: '#444',
    fontSize: 10,
  },
});
