import { StyleSheet } from 'react-native';
import { theme } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  listContent: {
    padding: 10,
    paddingBottom: 100,
  },
  objectCard: {
    width: '15.6%',
    backgroundColor: theme.colors.surface,
    padding: 6,
    borderRadius: 2,
    marginBottom: 10,
    marginHorizontal: '0.5%',
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
    minHeight: 80,
  },
  objectIcon: {
    width: 32,
    height: 32,
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    marginTop: 8,
  },
  objectInfo: {
    width: '100%',
    marginBottom: 4,
  },
  objectName: {
    fontSize: 10,
    fontWeight: 'bold',
    color: theme.colors.text,
    textAlign: 'center',
  },
  objectBehavior: {
    fontSize: 8,
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  fab: {
    position: 'absolute',
    bottom: 30,
    right: 30,
    width: 48,
    height: 48,
    borderRadius: 2,
    backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: theme.colors.surfaceElevated,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    padding: 8,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    ...theme.typography.h2,
    color: theme.colors.text,
  },
  closeText: {
    color: theme.colors.error,
    fontWeight: '600',
  },
  behaviorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 16,
    paddingBottom: 32,
  },
  behaviorButton: {
    width: '48%',
    backgroundColor: theme.colors.surface,
    padding: 8,
    borderRadius: 2,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  behaviorIcon: {
    width: 56,
    height: 56,
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  behaviorLabel: {
    ...theme.typography.body,
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.text,
  },
  inspectorOverlay: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  inspectorContent: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 32,
  },
  inspectorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  inspectorTitle: {
    ...theme.typography.h2,
    color: theme.colors.text,
  },
  saveText: {
    color: theme.colors.primary,
    fontWeight: 'bold',
    fontSize: 14,
  },
  inspectorSection: {
    backgroundColor: theme.colors.surface,
    borderRadius: 2,
    padding: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  sectionLabel: {
    ...theme.typography.body,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  inputGroup: {
    marginBottom: 16,
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.border,
    marginVertical: 8,
    opacity: 0.5,
  },
  subSectionTitle: {
    color: theme.colors.text,
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  listenerRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 12,
    marginBottom: 16,
    backgroundColor: '#1E2228',
    padding: 8,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  miniLabel: {
    color: theme.colors.textMuted,
    fontSize: 10,
    marginBottom: 4,
  },
  miniInput: {
    backgroundColor: '#2E333D',
    borderRadius: 2,
    padding: 6,
    color: theme.colors.text,
    fontSize: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minHeight: 32,
    justifyContent: 'center',
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 8,
    borderRadius: 2,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: theme.colors.primary,
    marginTop: 8,
  },
  addButtonText: {
    color: theme.colors.primary,
    fontSize: 12,
    fontWeight: 'bold',
  },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  readonlyValue: {
    color: theme.colors.primary,
    fontWeight: 'bold',
    textTransform: 'capitalize',
    fontSize: 14,
    backgroundColor: '#1E2228',
    padding: 8,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  inputLabel: {
    ...theme.typography.caption,
    marginBottom: 4,
    color: theme.colors.textMuted,
  },
  inspectorInput: {
    backgroundColor: theme.colors.surfaceElevated,
    borderRadius: 2,
    padding: 10,
    fontSize: 14,
    color: theme.colors.text,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  appearancePicker: {
    marginTop: 8,
  },
  spriteSelectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceElevated,
    padding: 10,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: theme.colors.border,
    gap: 12,
  },
  spritePreviewContainer: {
    width: 48,
    height: 48,
    backgroundColor: '#1E2228',
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  spriteSelectInfo: {
    flex: 1,
  },
  spriteSelectLabel: {
    color: theme.colors.text,
    fontSize: 14,
    fontWeight: 'bold',
  },
  spriteSelectSub: {
    color: theme.colors.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  pickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  pickerContent: {
    width: '100%',
    maxHeight: '70%',
    backgroundColor: theme.colors.surfaceElevated,
    borderRadius: 2,
    padding: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  pickerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    paddingBottom: 20,
  },
  pickerItem: {
    width: '30%',
    alignItems: 'center',
    gap: 4,
    marginBottom: 8,
  },
  pickerPreview: {
    width: 48,
    height: 48,
    backgroundColor: theme.colors.surface,
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  pickerLabel: {
    color: theme.colors.textMuted,
    fontSize: 10,
    textAlign: 'center',
  },
  emptyPicker: {
    padding: 40,
    alignItems: 'center',
    gap: 12,
  },
  emptyPickerText: {
    color: theme.colors.text,
    fontSize: 16,
    fontWeight: 'bold',
  },
  emptyPickerSub: {
    color: theme.colors.textMuted,
    fontSize: 14,
    textAlign: 'center',
  },
  logicPanel: {
    gap: 12,
  },
  switchLabel: {
    color: theme.colors.textSecondary,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 100,
  },
  emptyText: {
    ...theme.typography.caption,
    textAlign: 'center',
    marginTop: 16,
    maxWidth: 200,
  },
  subSectionTitleCompact: {
    color: theme.colors.text,
    fontSize: 10,
    fontWeight: 'bold',
    marginBottom: 8,
    marginTop: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
    opacity: 0.7,
  },
  pickerRowSmall: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
  },
  pickerChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceElevated,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  pickerChipText: {
    color: theme.colors.text,
    fontSize: 11,
    fontWeight: '500',
  },
  actionPresetItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    padding: 12,
    borderRadius: 2,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    gap: 12,
  },
  actionPresetText: {
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: '500',
  },
  pickerChipSecondary: {
    backgroundColor: '#2E333D',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  pickerChipTextSmall: {
    color: theme.colors.text,
    fontSize: 10,
    fontWeight: 'bold',
  },
  objectPickerItemSmall: {
    width: '31%',
    backgroundColor: theme.colors.surface,
    padding: 8,
    borderRadius: 2,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
    gap: 6,
  },
  objectPickerSpriteBox: {
    width: 40,
    height: 40,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  objectPickerNameSmall: {
    color: theme.colors.textMuted,
    fontSize: 8,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
