import { StyleSheet } from 'react-native';
import { theme } from '../../../../theme';

export const styles = StyleSheet.create({
  row: { flexDirection: 'row', gap: 12 },
  inspectorOverlay: { flex: 1, backgroundColor: theme.colors.background },
  inspectorContent: { flex: 1, paddingHorizontal: 0, paddingTop: 20 },
  inspectorHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: theme.colors.border, paddingHorizontal: 16 },
  inspectorTitle: { ...theme.typography.h3, color: theme.colors.text, fontWeight: 'bold' },
  saveText: { color: theme.colors.primary, fontWeight: 'bold', fontSize: 13 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalContent: { width: '100%', backgroundColor: theme.colors.surface, borderRadius: 8, padding: 12, borderWidth: 1, borderColor: theme.colors.border },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  modalTitle: { ...theme.typography.h3, color: theme.colors.text },
  inspectorSectionCompact: { backgroundColor: 'transparent', marginBottom: 4, overflow: 'hidden' },
  sectionHeaderAccordion: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 8, paddingHorizontal: 4, borderBottomWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  sectionLabel: { ...theme.typography.caption, fontWeight: 'bold', color: theme.colors.textSecondary, textTransform: 'uppercase', letterSpacing: 1, fontSize: 9 },
  sectionContent: { paddingVertical: 8, paddingHorizontal: 4, gap: 6 },
  propertyRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 4, minHeight: 32 },
  propertyLabel: { flex: 1, color: theme.colors.textMuted, fontSize: 11, fontWeight: '500' },
  propertyValue: { flex: 1.5, flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: 8 },
  inputGroupCompact: { flex: 1 },
  inputLabel: { ...theme.typography.caption, color: theme.colors.textMuted, fontSize: 9, marginBottom: 2 },
  inspectorInputCompact: { backgroundColor: '#16191E', borderRadius: 4, paddingHorizontal: 8, paddingVertical: 6, fontSize: 11, color: theme.colors.text, borderWidth: 1, borderColor: '#333', width: '100%' },
  spriteSelectButtonCompact: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#16191E', padding: 6, borderRadius: 4, gap: 8, borderWidth: 1, borderColor: '#333' },
  spritePreviewContainerSmall: { width: 28, height: 28, backgroundColor: '#000', borderRadius: 4, justifyContent: 'center', alignItems: 'center' },
  spriteSelectLabelSmall: { color: theme.colors.text, fontSize: 11, fontWeight: '600', flex: 1 },
  switchRowCompact: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 4 },
  animationStateRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#1E2228', padding: 8, borderRadius: 8 },
  animationStateLabel: { color: theme.colors.text, fontSize: 10, fontWeight: 'bold' },
  miniSpritePicker: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#2E333D', padding: 4, borderRadius: 6 },
  miniSpriteText: { color: theme.colors.textMuted, fontSize: 9 },
  subSection: { gap: 10, paddingLeft: 12, borderLeftWidth: 1, borderLeftColor: theme.colors.border, marginTop: 4 },
  divider: { height: 1, backgroundColor: theme.colors.border, marginVertical: 4 },
  soundRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  soundPicker: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#1E2228', padding: 6, borderRadius: 6, minWidth: 120 },
  soundText: { color: theme.colors.text, fontSize: 10 },
  subSectionTitleCompact: { color: theme.colors.textMuted, fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: 0.5 },
  variableRow: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  varName: { flex: 1, backgroundColor: '#1E2228', padding: 6, borderRadius: 4, color: theme.colors.text, fontSize: 10 },
  varValue: { flex: 1, backgroundColor: '#1E2228', padding: 6, borderRadius: 4, color: theme.colors.primary, fontSize: 10 },
  varActions: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  addButtonCompact: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, padding: 8, borderRadius: 8, borderWidth: 1, borderStyle: 'dashed', borderColor: theme.colors.primary },
  addButtonTextSmall: { color: theme.colors.primary, fontSize: 10, fontWeight: 'bold' },
  infoTextSmall: { color: theme.colors.textMuted, fontSize: 9, textAlign: 'center', marginTop: 8, fontStyle: 'italic' },
  miniObjectSelect: { padding: 8, borderRadius: 10, backgroundColor: '#1E2228', alignItems: 'center', gap: 6, marginRight: 8, borderWidth: 1, borderColor: 'transparent', minWidth: 80 },
  miniObjectSelectActive: { borderColor: theme.colors.primary, backgroundColor: theme.colors.surfaceElevated },
  miniObjectText: { color: theme.colors.text, fontSize: 9, fontWeight: '600' },
  previewContainer: { height: 100, backgroundColor: '#000', borderRadius: 4, marginBottom: 12, overflow: 'hidden', position: 'relative', borderBottomWidth: 1, borderColor: '#333' },
  previewParticle: { position: 'absolute', width: 4, height: 4, borderRadius: 2 },
  previewSource: { position: 'absolute', bottom: 10, left: '50%', marginLeft: -4, width: 8, height: 8, borderRadius: 4, backgroundColor: '#fff', opacity: 0.3 },
  actionPresetItem: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 12, backgroundColor: '#1E2228', borderRadius: 8, marginTop: 8 },
  actionPresetText: { color: theme.colors.text, fontSize: 14, fontWeight: '600' },
  miniLabel: {
    color: theme.colors.textMuted,
    fontSize: 10,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  miniInput: {
    backgroundColor: '#2E333D',
    borderRadius: 6,
    padding: 8,
    color: theme.colors.text,
    fontSize: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minHeight: 36,
    justifyContent: 'center',
  },
  logicChainContainer: { marginBottom: 12, borderRadius: 4, borderWidth: 1, borderColor: '#333', backgroundColor: '#0A0C10', overflow: 'hidden' },
  logicBlockHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4, marginLeft: 4 },
  logicBlockTitle: { color: theme.colors.textMuted, fontSize: 8, fontWeight: 'bold', textTransform: 'uppercase' },
  logicBlock: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#1E2228', padding: 4, borderRadius: 2, borderWidth: 1, borderColor: '#333' },
  logicInput: { flex: 1, color: theme.colors.text, fontSize: 10, padding: 0, height: '100%' },
  logicConnector: { width: 1, height: 10, backgroundColor: '#333', marginLeft: 12 },
  logicConnectorSmall: { width: 1, height: 6, backgroundColor: '#333', marginLeft: 8, marginBottom: 2 },
  addConditionBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 10, padding: 6, borderRadius: 6, borderWidth: 1, borderStyle: 'dashed', borderColor: theme.colors.primary + '60', alignSelf: 'flex-start', marginLeft: 4 },
  addConditionText: { color: theme.colors.primary, fontSize: 8, fontWeight: 'bold' },
  logicDeleteButton: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 12, alignSelf: 'flex-end', opacity: 0.7 },
  pickerRowSmall: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  pickerChip: { backgroundColor: '#2E333D', paddingHorizontal: 16, paddingVertical: 12, borderRadius: 10, borderWidth: 1, borderColor: '#444' },
  pickerChipSecondary: { backgroundColor: '#1E2228', paddingHorizontal: 14, paddingVertical: 10, borderRadius: 8, borderWidth: 1, borderColor: '#333' },
  pickerChipText: { color: theme.colors.text, fontSize: 13, fontWeight: 'bold' },
  pickerChipTextSmall: { color: theme.colors.textMuted, fontSize: 11, fontWeight: 'bold' },
  objectPickerItemSmall: { width: '22%', backgroundColor: '#1E2228', borderRadius: 8, padding: 6, alignItems: 'center', gap: 4, borderWidth: 1, borderColor: '#333' },
  objectPickerSpriteBox: { width: 32, height: 32, backgroundColor: '#2E333D', borderRadius: 4, justifyContent: 'center', alignItems: 'center' },
  objectPickerNameSmall: { color: theme.colors.text, fontSize: 8, fontWeight: 'bold', textAlign: 'center' },
  appearanceTypeRow: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  typeChip: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: 8, backgroundColor: '#1E2228', borderWidth: 1, borderColor: theme.colors.border },
  typeChipActive: { backgroundColor: theme.colors.primary + '20', borderColor: theme.colors.primary },
  typeChipText: { color: theme.colors.textMuted, fontSize: 11, fontWeight: 'bold' },
  typeChipTextActive: { color: theme.colors.primary },
  menuContainer: {
    backgroundColor: theme.colors.surface,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: theme.colors.border,
    overflow: 'hidden',
  },
  menuHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    backgroundColor: theme.colors.surfaceElevated,
  },
  menuTitle: {
    ...theme.typography.h3,
    color: theme.colors.text,
    fontSize: 14,
    fontWeight: 'bold',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    gap: 12,
  },
  menuText: {
    color: theme.colors.text,
    fontSize: 13,
  },
  previewHeader: {
    padding: 20,
    alignItems: 'center',
    backgroundColor: '#0A0C10',
    borderBottomWidth: 1,
    borderBottomColor: '#222',


  },
  previewBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  previewBadgeText: {
    color: theme.colors.textMuted,
    fontSize: 9,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  }
});
