import { StyleSheet } from 'react-native';
import { theme } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: theme.colors.background,
  },
  floatingLeftTools: {
    position: 'absolute',
    left: 30,
    top: 12,
    backgroundColor: '#16191E',
    padding: 2,
    borderRadius: 2,
    gap: 4,
    borderWidth: 1,
    borderColor: theme.colors.border,
    zIndex: 100,
  },
  toolButton: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 2,
    backgroundColor: '#1E2228',
  },
  toolActive: {
    backgroundColor: theme.colors.primary + '20',
    borderColor: theme.colors.primary,
    borderWidth: 1,
  },
  mainEditorArea: {
    flex: 1,
    backgroundColor: '#1E2228',
    justifyContent: 'center',
    alignItems: 'center',
  },
  room: {
    backgroundColor: '#2E333D',
    borderWidth: 1,
    borderColor: '#3F4551',
  },
  gestureOverlay: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  instance: {
    position: 'absolute',
    left: 0,
    top: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 209, 255, 0.1)',
  },
  resizeHandleRight: {
    position: 'absolute',
    right: -10,
    top: '50%',
    marginTop: -12,
    width: 24,
    height: 24,
    backgroundColor: theme.colors.primary,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 110,
    borderWidth: 2,
    borderColor: 'white',
  },
  resizeHandleBottom: {
    position: 'absolute',
    bottom: -10,
    left: '50%',
    marginLeft: -12,
    width: 24,
    height: 24,
    backgroundColor: theme.colors.primary,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 110,
    borderWidth: 2,
    borderColor: 'white',
  },
  gridLineH: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    zIndex: 200,
  },
  gridLineV: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    zIndex: 200,
  },
  layersList: {
    marginTop: 8,
  },
  layerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    backgroundColor: 'rgba(255,255,255,0.02)',

    marginBottom: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  layerItemActive: {
    backgroundColor: 'rgba(0, 209, 255, 0.08)',
    borderColor: theme.colors.primary,
    borderLeftWidth: 1,
    borderLeftColor: theme.colors.primary,
  },
  layerInfo: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  layerPreview: {
    width: 24,
    height: 24,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  layerName: {
    color: '#E2E8F0',
    fontSize: 12,
    fontWeight: '500',
  },
  layerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  zoomControls: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    flexDirection: 'row',
    gap: 4,
    backgroundColor: '#16191E',
    padding: 2,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: theme.colors.border,
    zIndex: 50,
  },
  zoomButton: {
    padding: 6,
  },
  toggleButton: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    width: 36,
    height: 36,
    backgroundColor: '#16191E',
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
    zIndex: 100,
  },
  toggleButtonOff: {
    opacity: 0.6,
  },
  sidebarToggle: {
    position: 'absolute',
    right: 0,
    top: '50%',
    marginTop: -16,
    width: 20,
    height: 32,
    backgroundColor: '#16191E',
    borderTopLeftRadius: 6,
    borderBottomLeftRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderRightWidth: 0,
    borderColor: theme.colors.border,
    zIndex: 110,
  },
  sidebarToggleOpen: {
    right: 230,
  },
  sidebar: {
    width: 230,
    backgroundColor: '#16191E',
    borderLeftWidth: 1,
    borderLeftColor: theme.colors.border,
    zIndex: 105,
  },
  sidebarSection: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  sectionTitle: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
    opacity: 0.9,
  },
  roomTab: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: '#1E2228',
    borderRadius: 2,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  roomTabActive: {
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.primary + '10',
  },
  objectGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  objectItem: {
    width: '48%',
    alignItems: 'center',
    padding: 6,
    borderRadius: 2,
    backgroundColor: '#1E2228',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  objectItemActive: {
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.primary + '10',
  },
  objectPreview: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 2,
    overflow: 'hidden',
  },
  objectName: {
    color: theme.colors.textMuted,
    fontSize: 9,
    textAlign: 'center',
  },
  emptySidebar: {
    padding: 20,
    alignItems: 'center',
    gap: 8,
  },
  emptySidebarText: {
    color: theme.colors.textMuted,
    fontSize: 10,
    textAlign: 'center',
  },
  settingsList: {
    gap: 10,
  },
  settingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  settingLabel: {
    color: theme.colors.textMuted,
    fontSize: 11,
  },
  settingInput: {
    color: theme.colors.text,
    fontSize: 11,
    fontWeight: '600',
    backgroundColor: '#2E333D',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 2,
    minWidth: 50,
    textAlign: 'right',
  },
  toggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#1E2228',
    padding: 8,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  toggleRowActive: {
    borderColor: theme.colors.primary + '40',
    backgroundColor: theme.colors.primary + '05',
  },
  toggleText: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  toggleTextActive: {
    color: theme.colors.text,
  },
  toggleIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#3F4551',
  },
  toggleIndicatorActive: {
    backgroundColor: theme.colors.primary,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
  },
  targetOption: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: '#1E2228',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  targetOptionActive: {
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.primary + '20',
  },
  targetOptionText: {
    color: theme.colors.textMuted,
    fontSize: 10,
    fontWeight: '600',
  },
  targetOptionTextActive: {
    color: theme.colors.text,
  },
  dropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1E2228',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minWidth: 100,
    marginTop: 4,
  },
  dropdownText: {
    color: theme.colors.text,
    fontSize: 12,
    flex: 1,
    marginRight: 8,
  },
  pickerOverlay: {

    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
  },
  pickerContent: {
    width: '100%',
    maxHeight: '100%',
    backgroundColor: '#1E2228',

    borderWidth: 1,
    borderColor: theme.colors.border,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  pickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 5,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border + '40',
  },
  pickerTitle: {
    color: theme.colors.text,
    fontSize: 14,
    fontWeight: 'bold',
  },
  pickerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 12,
    gap: 12,
  },
  pickerGridItem: {
    width: '15%',
    aspectRatio: 1,
    backgroundColor: '#1E2228',

    borderWidth: 1,
    borderColor: theme.colors.border,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
  },
  pickerGridItemActive: {
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.primary + '15',
  },
  pickerPreviewBox: {
    width: '100%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  pickerGridLabel: {
    color: theme.colors.textMuted,
    fontSize: 10,
    textAlign: 'center',
    width: '100%',
  },
  pickerGridLabelActive: {
    color: theme.colors.text,
    fontWeight: 'bold',
  },
});
