import { StyleSheet } from 'react-native';
import { theme } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: theme.colors.background,
  },
  floatingLeftTools: {
    position: 'absolute',
    left: 12,
    top: 12,
    backgroundColor: '#16191E',
    padding: 6,
    borderRadius: 6,
    gap: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    zIndex: 100,
  },
  toolButton: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
    backgroundColor: '#1E2228',
  },
  toolActive: {
    backgroundColor: theme.colors.primary + '20',
    borderColor: theme.colors.primary,
    borderWidth: 1,
  },
  mainEditorArea: {
    flex: 1,
    backgroundColor: '#1E2228',
    justifyContent: 'center',
    alignItems: 'center',
  },
  room: {
    backgroundColor: '#2E333D',
    borderWidth: 1,
    borderColor: '#3F4551',
  },
  gestureOverlay: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  instance: {
    position: 'absolute',
    left: 0,
    top: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 209, 255, 0.1)',
  },
  resizeHandleRight: {
    position: 'absolute',
    right: -10,
    top: '50%',
    marginTop: -12,
    width: 24,
    height: 24,
    backgroundColor: theme.colors.primary,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 110,
    borderWidth: 2,
    borderColor: 'white',
  },
  resizeHandleBottom: {
    position: 'absolute',
    bottom: -10,
    left: '50%',
    marginLeft: -12,
    width: 24,
    height: 24,
    backgroundColor: theme.colors.primary,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 110,
    borderWidth: 2,
    borderColor: 'white',
  },
  gridLineH: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    zIndex: 200,
  },
  gridLineV: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    zIndex: 200,
  },
  layersList: {
    marginTop: 8,
  },
  layerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 8,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  layerItemActive: {
    backgroundColor: 'rgba(0, 209, 255, 0.1)',
    borderColor: theme.colors.primary,
  },
  layerInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  layerPreview: {
    width: 24,
    height: 24,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  layerName: {
    color: theme.colors.text,
    fontSize: 12,
  },
  layerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  zoomControls: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    flexDirection: 'row',
    gap: 6,
    backgroundColor: '#16191E',
    padding: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: theme.colors.border,
    zIndex: 50,
  },
  zoomButton: {
    padding: 6,
  },
  toggleButton: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    width: 36,
    height: 36,
    backgroundColor: '#16191E',
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
    zIndex: 100,
  },
  toggleButtonOff: {
    opacity: 0.6,
  },
  sidebarToggle: {
    position: 'absolute',
    right: 0,
    top: '50%',
    marginTop: -16,
    width: 20,
    height: 32,
    backgroundColor: '#16191E',
    borderTopLeftRadius: 6,
    borderBottomLeftRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderRightWidth: 0,
    borderColor: theme.colors.border,
    zIndex: 110,
  },
  sidebarToggleOpen: {
    right: 180,
  },
  sidebar: {
    width: 180,
    backgroundColor: '#16191E',
    borderLeftWidth: 1,
    borderLeftColor: theme.colors.border,
    paddingTop: 8,
    zIndex: 105,
  },
  sidebarSection: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border + '40',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  sectionTitle: {
    color: theme.colors.text,
    fontSize: 10,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  roomTab: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: '#1E2228',
    borderRadius: 6,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  roomTabActive: {
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.primary + '10',
  },
  objectGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  objectItem: {
    width: '47%',
    alignItems: 'center',
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#1E2228',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  objectItemActive: {
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.primary + '10',
  },
  objectPreview: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 2,
    overflow: 'hidden',
  },
  objectName: {
    color: theme.colors.textMuted,
    fontSize: 9,
    textAlign: 'center',
  },
  emptySidebar: {
    padding: 20,
    alignItems: 'center',
    gap: 8,
  },
  emptySidebarText: {
    color: theme.colors.textMuted,
    fontSize: 10,
    textAlign: 'center',
  },
  settingsList: {
    gap: 10,
  },
  settingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  settingLabel: {
    color: theme.colors.textMuted,
    fontSize: 11,
  },
  settingInput: {
    color: theme.colors.text,
    fontSize: 11,
    fontWeight: '600',
    backgroundColor: '#2E333D',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    minWidth: 50,
    textAlign: 'right',
  },
  toggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#1E2228',
    padding: 8,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  toggleRowActive: {
    borderColor: theme.colors.primary + '40',
    backgroundColor: theme.colors.primary + '05',
  },
  toggleText: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  toggleTextActive: {
    color: theme.colors.text,
  },
  toggleIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#3F4551',
  },
  toggleIndicatorActive: {
    backgroundColor: theme.colors.primary,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
  },
});
